# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded metagui3 3.0 [list source [file join $dir metagui3.tcl]]\n[list source [file join $dir metagui3_ui.tcl]]

package ifneeded sframe 1.0 [list source [file join $dir sframe.tcl]]

# TG - not sure if good practice; it works.
if { [file join $dir tablelist5.15] ni $auto_path } {
    lappend auto_path  [file join $dir tablelist5.15]
}

